"""Generate ruff.toml and ruff.warn.toml from rules/register.toml.

The register records a decision for every rule the pinned Ruff knows:
  block  selected in ruff.toml; fails CI and pre-commit
  warn   selected in ruff.warn.toml; run with --exit-zero, never fails
  off    not selected; a reason is required
Rules with autofix = false go in lint.unfixable so `ruff check --fix` never rewrites them.

Usage:
  python scripts/build_config.py           # validate the register and write both configs
  python scripts/build_config.py --check   # fail if the committed configs are out of date
"""

import argparse
import copy
import json
import pathlib
import re
import subprocess
import sys
import tomllib

STATUSES = ("block", "warn", "off")
BLOCK_FILE = "ruff.toml"
WARN_FILE = "ruff.warn.toml"
REGISTER_FILE = pathlib.Path("rules") / "register.toml"
GENERATED_HEADER = (
    "# Generated by scripts/build_config.py from rules/register.toml. Do not edit by hand.\n"
    "# Change the register, then run: python scripts/build_config.py\n"
)
REGISTER_HEADER = (
    "# Rule register: one decision per Ruff rule. This file is the source of truth.\n"
    "# status: block (fails CI), warn (reported, never fails), off (not selected; reason required).\n"
    "# autofix = false keeps `ruff check --fix` away from the rule.\n"
    "# After editing, run: python scripts/build_config.py\n"
)
BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")
INLINE_LIST_LIMIT = 100


def load_catalog(ruff: str) -> dict:
    """Return {code: {"name", "fix"}} for every selectable rule of the installed Ruff."""
    result = subprocess.run(
        [ruff, "rule", "--all", "--output-format", "json"], capture_output=True, text=True, check=True
    )
    catalog = {}
    for rule in json.loads(result.stdout):
        if rule["code"] and "Removed" not in rule["status"]:
            catalog[rule["code"]] = {"name": rule["name"], "fix": rule["fix_availability"]}
    return catalog


def validate_rule(rule: dict, catalog: dict) -> list[str]:
    """Return the problems with one register entry."""
    code = rule.get("code", "?")
    if code not in catalog:
        return [f"{code}: unknown to the installed Ruff; remove it or upgrade Ruff"]
    errors = []
    if rule.get("name") != catalog[code]["name"]:
        errors.append(f"{code}: name {rule.get('name')!r} should be {catalog[code]['name']!r}")
    if rule.get("status") not in STATUSES:
        errors.append(f"{code}: status {rule.get('status')!r} must be one of {', '.join(STATUSES)}")
    if not isinstance(rule.get("autofix"), bool):
        errors.append(f"{code}: autofix must be true or false")
    if rule.get("status") == "off" and not str(rule.get("reason", "")).strip():
        errors.append(f"{code}: off rules need a reason")
    return errors


def validate_register(rules: list[dict], catalog: dict) -> list[str]:
    """Return every disagreement between the register and the Ruff catalog."""
    errors = []
    seen = set()
    for rule in rules:
        code = rule.get("code", "?")
        if code in seen:
            errors.append(f"{code}: duplicate entry")
        seen.add(code)
        errors.extend(validate_rule(rule, catalog))
    errors.extend(f"{code}: undecided; add it to the register" for code in sorted(set(catalog) - seen))
    return errors


def format_string(value: str) -> str:
    """Return a TOML basic string holding value.

    JSON escapes are valid TOML escapes, but with ensure_ascii JSON writes astral characters as
    surrogate pairs, which TOML rejects. Without it, JSON still escapes quotes, backslashes and
    U+0000 to U+001F, leaving only DEL, which TOML also forbids raw.
    """
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")


def format_key(key: str) -> str:
    """Return a TOML key, quoted when it is not a bare key."""
    return key if BARE_KEY.match(key) else format_string(key)


def format_value(value: object) -> str:
    """Return a TOML literal for a scalar or a list of scalars.

    Raises:
        TypeError: The value is not a bool, number, string or list of those.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return format_string(value)
    if isinstance(value, list):
        items = [format_value(item) for item in value]
        inline = "[" + ", ".join(items) + "]"
        if len(inline) <= INLINE_LIST_LIMIT:
            return inline
        return "[\n" + "".join(f"  {item},\n" for item in items) + "]"
    raise TypeError(f"Cannot write {type(value).__name__} to TOML")


def format_table(table: dict, path: tuple[str, ...]) -> list[str]:
    """Return TOML lines for a table: its scalars first, then its sub-tables."""
    lines = []
    scalars = {k: v for k, v in table.items() if not isinstance(v, dict)}
    if path and scalars:
        lines.append("[" + ".".join(format_key(p) for p in path) + "]")
    lines.extend(f"{format_key(k)} = {format_value(v)}" for k, v in scalars.items())
    for key, value in table.items():
        if isinstance(value, dict):
            if lines:
                lines.append("")
            lines.extend(format_table(value, (*path, key)))
    return lines


def names_with(rules: list[dict], statuses: tuple[str, ...], autofix: bool | None = None) -> list[str]:
    """Return sorted rule names with a status in `statuses`, optionally filtered by autofix."""
    return sorted(r["name"] for r in rules if r["status"] in statuses and (autofix is None or r["autofix"] is autofix))


def render_block_config(settings: dict, rules: list[dict]) -> str:
    """Return ruff.toml: the settings plus every block rule, selected by name."""
    config = copy.deepcopy(settings)
    lint = config.setdefault("lint", {})
    lint["select"] = names_with(rules, ("block",))
    # Warn rules are listed too: ruff.warn.toml extends this file and inherits the list.
    lint["unfixable"] = names_with(rules, ("block", "warn"), autofix=False)
    lint = {"select": lint.pop("select"), "unfixable": lint.pop("unfixable"), **lint}
    config["lint"] = lint
    return GENERATED_HEADER + "\n" + "\n".join(format_table(config, ())) + "\n"


def render_warn_config(rules: list[dict]) -> str:
    """Return ruff.warn.toml: ruff.toml's settings with only the warn rules selected."""
    config = {"extend": BLOCK_FILE, "lint": {"select": names_with(rules, ("warn",))}}
    usage = "# Run with: ruff check --config ruff.warn.toml --exit-zero\n"
    return GENERATED_HEADER + usage + "\n" + "\n".join(format_table(config, ())) + "\n"


def render_register(settings: dict, rules: list[dict]) -> str:
    """Return register TOML for the given settings and rules, sorted by code."""
    lines = format_table({"settings": settings}, ())
    for rule in sorted(rules, key=lambda r: r["code"]):
        lines.extend(["", "[[rule]]"])
        lines.extend(f"{key} = {format_value(rule[key])}" for key in ("code", "name", "status", "autofix", "reason"))
    return REGISTER_HEADER + "\n" + "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command-line options.

    Returns:
        The parsed options.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    parser.add_argument(
        "--root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent,
        help="repository root (default: this script's repo)",
    )
    parser.add_argument("--ruff", default="ruff", help="Ruff executable used to read the rule catalog")
    parser.add_argument(
        "--catalog", type=pathlib.Path, help="JSON {code: {name, fix}} to use instead of asking Ruff (for tests)"
    )
    return parser.parse_args(argv)


def report_drift(root: pathlib.Path, outputs: dict[str, str]) -> int:
    """Name each generated file that differs from what the register produces.

    Returns:
        1 if any file is stale or missing, else 0.
    """
    stale = [
        name
        for name, text in outputs.items()
        if not (root / name).exists() or (root / name).read_text(encoding="utf-8") != text
    ]
    for name in stale:
        print(f"{name} is out of date with {REGISTER_FILE}. Run: python scripts/build_config.py", file=sys.stderr)
    return 1 if stale else 0


def main(argv: list[str] | None = None) -> int:
    """Validate the register, then write or check the generated configs.

    Returns:
        The process exit code: 0 on success, 1 on an invalid register or drift.
    """
    args = parse_args(sys.argv[1:] if argv is None else argv)
    register = tomllib.loads((args.root / REGISTER_FILE).read_text(encoding="utf-8"))
    rules = register.get("rule", [])
    if args.catalog:
        catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    else:
        catalog = load_catalog(args.ruff)
    errors = validate_register(rules, catalog)
    for error in errors:
        print(error, file=sys.stderr)
    if errors:
        print(f"{len(errors)} problem(s) in {REGISTER_FILE}; nothing written.", file=sys.stderr)
        return 1
    outputs = {
        BLOCK_FILE: render_block_config(register.get("settings", {}), rules),
        WARN_FILE: render_warn_config(rules),
    }
    if args.check:
        return report_drift(args.root, outputs)
    for name, text in outputs.items():
        (args.root / name).write_text(text, encoding="utf-8")
    counts = {s: sum(1 for r in rules if r["status"] == s) for s in STATUSES}
    print(f"Wrote {BLOCK_FILE} ({counts['block']} block) and {WARN_FILE} ({counts['warn']} warn); {counts['off']} off.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
